plugins {
    id "com.android.application"
}

android {
    namespace "com.ppcodigo.totemspanishiso"
    compileSdk 35

    defaultConfig {
        applicationId "com.ppcodigo.totemspanishiso"
        minSdk 21
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
